---
title: "Blog 5"
author: "Collin Knezevich"
date: '2022-07-26'
output: github_document
---

I enjoy using R for data science and I think is a great tool. There are countless packages to help you do what you need, and it is great to have access to these resources. I would like to continue to use R going forward, but it ultimately depends on what tools are used at my future job. If my job allows for flexibility in terms of what tools we use, then I would likely choose to use R.   

Something I might do differently after taking this course is to utilize Shiny apps where applicable. These apps are a very powerful tool so I would like to continue to learn about them and improve my skills using them.   

Another area of statistics/data science I would like to continue learning about is model selection, and choosing candidate models. Unless I have prior knowledge about the specific data I'm working with, I find it hard to choose candidate models and narrow down the variables of interest. I would like to improve in this area and learn more techniques for this. 